=head1 NAME

LibEvent::EventBase - Representation of event base from libevent2

=head1 CONSTRUCTOR

=head2 LibEvent::EventBase->new

Create new EventBase object.

=head1 METHODS

=head2 $base->event_new($fh, $events, $cb)

Create new IO event.
Returns L<LibEvent::EvIO> object

=head2 $base->signal_new($signum, $events, $cb)

Create new signal event.
Returns L<LibEvent::EvSignal> object

=head2 $base->timer_new($events, $cb)

Create new timer event.
Returns L<LibEvent::EvTimer> object

=head2 $base->loop($flags)

Wait for events to become active and run their callbacks.
This loop will run the event base until either there are no more added events, or until something calls break method.

B<Parameters>:

=over

=item C<$flags> - bit mask (optional). Can contains L<EVLOOP_ONCE|LibEvent/EVLOOP_ONCE> and/or L<EVLOOP_NONBLOCK|LibEvent/EVLOOP_NONBLOCK>.

=back

B<Returns>: 0 if successful, -1 if an error occurred and 1 if no events were registered.

=head2 $base->break

=head2 $base->reinit

=head2 $base->get_method

