=head1 NAME

LibEvent::EvIO - IO event

=head1 METHODS

=head2 $ev->add($timeout)

Make event pending in its base.

$timeout - the maximum amount of time to wait for the event, or undef to wait forever

=head2 $ev->events

Returns events that this watcher listen

=head2 $ev->io

Returns filehandle for this watcher
