=head1 NAME

LibEvent::Event - Timer event

=head1 METHODS

=head2 $ev->add($timeout)

Make event pending in its base.

$timeout - the maximum amount of time to wait for the event, or undef to wait forever

=head2 $ev->del

Remove an event from the set of monitored events. If the event has already executed or has never been added the call will have no effect.

=head2 $ev->events

Returns events that this watcher listen

=head2 $ev->pending

Returns 1 if the event is pending to run, otherwise 0.
